export const ALL_BOOK_CATEGORIES = [
  "Literatura Brasileira",
  "Literatura Estrangeira",
  "Romance",
  "Ficção",
  "Ficção Científica",
  "Fantasia",
  "Terror",
  "Suspense e Mistério",
  "Policial",
  "Drama",
  "Poesia",
  "Contos e Crônicas",
  "Infantojuvenil",
  "Infantil",
  "HQ e Quadrinhos",
  "Mangá",
  "Biografia e Memórias",
  "História",
  "Filosofia",
  "Sociologia",
  "Psicologia",
  "Política",
  "Religião e Espiritualidade",
  "Autoajuda",
  "Negócios e Empreendedorismo",
  "Economia",
  "Direito",
  "Educação",
  "Pedagogia",
  "Saúde e Bem-estar",
  "Medicina",
  "Enfermagem",
  "Nutrição",
  "Ciência e Tecnologia",
  "Matemática",
  "Física",
  "Química",
  "Biologia",
  "Informática e Programação",
  "Engenharia",
  "Arquitetura e Design",
  "Artes e Fotografia",
  "Música",
  "Cinema e Teatro",
  "Culinária e Gastronomia",
  "Esportes e Lazer",
  "Turismo e Viagens",
  "Idiomas",
  "Dicionários e Gramáticas",
  "Concurso e Vestibular",
  "Didáticos e Acadêmicos",
  "Técnico e Profissionalizante",
  "Geografia",
  "Outros",
] as const;

export type BookCategory = (typeof ALL_BOOK_CATEGORIES)[number];

