ALTER TABLE sebos ADD COLUMN supportsPickup INTEGER DEFAULT 1;
ALTER TABLE sebos ADD COLUMN shipsNeighborhood INTEGER DEFAULT 0;
ALTER TABLE sebos ADD COLUMN shipsCity INTEGER DEFAULT 0;
ALTER TABLE sebos ADD COLUMN shipsState INTEGER DEFAULT 0;
ALTER TABLE sebos ADD COLUMN shipsNationwide INTEGER DEFAULT 0;
ALTER TABLE sebos ADD COLUMN shippingAreas TEXT;
ALTER TABLE sebos ADD COLUMN shippingFeeNotes TEXT;
ALTER TABLE sebos ADD COLUMN shippingEta TEXT;
ALTER TABLE sebos ADD COLUMN shippingNotes TEXT;
