ALTER TABLE sebos ADD COLUMN plan TEXT NOT NULL DEFAULT 'free';
ALTER TABLE sebos ADD COLUMN proSlug TEXT;
ALTER TABLE sebos ADD COLUMN proEnabledAt INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS idx_sebos_pro_slug ON sebos(proSlug) WHERE proSlug IS NOT NULL;
